import styles from "./Bookshelf.module.css";

import type { BookshelfConfig, BookshelfData, BookshelfTheme } from "@dawdle.space/bookshelf";
import { renderShelf } from "@dawdle.space/bookshelf";

interface Props {
	shelf: BookshelfData | null;
	loading: boolean;
	config: BookshelfConfig | null;
	theme: Exclude<BookshelfTheme, "auto">;
}

export function BookshelfPreview({ shelf, loading, config, theme }: Props) {
	return (
		<div className={styles.content}>
			{loading ? (
				<div className={styles.loadingState} role="status" aria-live="polite">
					<span className={styles.spinner} aria-hidden="true" />
					<p className={styles.state}>Loading your books…</p>
					<p className={styles.note}>This might take a while the first time.</p>
				</div>
			) : shelf && config ? (
				// biome-ignore lint/security/noDangerouslySetInnerHtml: previewing HTML generated by this package's renderer.
				<div dangerouslySetInnerHTML={{ __html: renderShelf(shelf, { ...config, theme }) }} />
			) : (
				<p className={styles.state}>Paste or type a Goodreads URL to load your shelf.</p>
			)}
		</div>
	);
}
