import type { Bookshelf, BookshelfConfig, BookshelfTheme } from "@explodingcamera/bookshelf";
import { renderShelf } from "@explodingcamera/bookshelf";
import styles from "./Bookshelf.module.css";

interface Props {
	shelf: Bookshelf | null;
	loading: boolean;
	config: BookshelfConfig | null;
	theme: Exclude<BookshelfTheme, "auto">;
}

export function BookshelfPreview({ shelf, loading, config, theme }: Props) {
	return (
		<div className={styles.content}>
			{loading ? (
				<p className={styles.state}>Loading your books…</p>
			) : shelf && config ? (
				// biome-ignore lint/security/noDangerouslySetInnerHtml: previewing HTML generated by this package's renderer.
				<div dangerouslySetInnerHTML={{ __html: renderShelf(shelf, { ...config, theme }) }} />
			) : (
				<p className={styles.state}>Paste a Goodreads URL and hit Generate.</p>
			)}
		</div>
	);
}
